set SOURCE_DIR=..\..
set BUILD_DIR=build
set BUILD_TYPE=Release
set BUILD_GEN=Visual Studio 17 2022
set BUILD_SHARED_LIBS=OFF

IF EXIST %BUILD_DIR% rmdir %BUILD_DIR% /s /q
mkdir %BUILD_DIR%
cd %BUILD_DIR%

cmake -S "%SOURCE_DIR%" -G "%BUILD_GEN%" -A x64 ^
-DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
-DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% ^
-DMINIMIZE_SIZE=ON ^
-DBUILD_WITH_STATIC_CRT=OFF

cmake --build . --config %BUILD_TYPE%
